services:
- type: web
  name: coolapp-backend-prod
  env: docker
  region: oregon
  plan: starter
  branch: master
  dockerfilePath: ./nest-app/Dockerfile
  dockerContext: ./nest-app

databases:
- name: coolapp-prod
  databaseName: coolapp_production
  user: coolapp_production_user
